"""add trends table

Revision ID: 21712fe4d17c
Revises: feebc4d387cc
Create Date: 2026-08-21 14:24:29.035459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21712fe4d17c'
down_revision: Union[str, None] = 'feebc4d387cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trends',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('trend_type', sa.Enum('LINEAR', 'EXPONENTIAL', 'LOGISTIC', 'SEASONAL', 'CYCLIC', 'RANDOM_WALK', name='trendtype'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['entity_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trends')
    # ### end Alembic commands ###
