"""add geo routes table

Revision ID: 26e22bd3e2c7
Revises: b3227be5dbd4
Create Date: 2026-08-21 18:14:46.844818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26e22bd3e2c7'
down_revision: Union[str, None] = 'b3227be5dbd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('lookup_table_id', sa.Uuid(), nullable=False),
    sa.Column('lat_column', sa.String(length=255), nullable=False),
    sa.Column('lon_column', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['entity_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lookup_table_id'], ['lookup_tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo_routes')
    # ### end Alembic commands ###
