"""add event triggers table

Revision ID: 2799f0b07920
Revises: 4d100104cd4f
Create Date: 2026-08-21 15:28:59.773073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2799f0b07920'
down_revision: Union[str, None] = '4d100104cd4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_triggers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('condition', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_triggers')
    # ### end Alembic commands ###
