"""add websocket_streams table

Revision ID: 27e7e338d49b
Revises: a974023dce47
Create Date: 2026-08-21 13:18:33.787256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27e7e338d49b'
down_revision: Union[str, None] = 'a974023dce47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websocket_streams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('events_per_second', sa.Float(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websocket_streams_token'), 'websocket_streams', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_websocket_streams_token'), table_name='websocket_streams')
    op.drop_table('websocket_streams')
    # ### end Alembic commands ###
