"""add plugin outputs table

Revision ID: 4253f7bc99a0
Revises: c938ee6e6169
Create Date: 2026-08-21 21:52:19.624133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4253f7bc99a0'
down_revision: Union[str, None] = 'c938ee6e6169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_outputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('plugin_name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('events_per_second', sa.Float(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plugin_outputs')
    # ### end Alembic commands ###
