"""add error injections table

Revision ID: 8961940e9e7f
Revises: 21712fe4d17c
Create Date: 2026-08-21 14:49:20.691576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8961940e9e7f'
down_revision: Union[str, None] = '21712fe4d17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_injections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('error_types', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['entity_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('error_injections')
    # ### end Alembic commands ###
