"""add timeline replays table

Revision ID: 9486abc9bbe0
Revises: ed897c9b439e
Create Date: 2026-08-21 16:10:50.074291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9486abc9bbe0'
down_revision: Union[str, None] = 'ed897c9b439e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_replays',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('lookup_table_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp_column', sa.String(length=255), nullable=False),
    sa.Column('speed_multiplier', sa.Float(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lookup_table_id'], ['lookup_tables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_replays_token'), 'timeline_replays', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_replays_token'), table_name='timeline_replays')
    op.drop_table('timeline_replays')
    # ### end Alembic commands ###
