"""add rules table and formula field

Revision ID: a6585bd46faf
Revises: acc4b09db89e
Create Date: 2026-08-21 02:32:54.501821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a6585bd46faf'
down_revision: Union[str, None] = 'acc4b09db89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('condition', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entity_fields', sa.Column('formula', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_fields', 'formula')
    op.drop_table('rules')
    # ### end Alembic commands ###
