"""add rest_outputs table

Revision ID: a974023dce47
Revises: b52c69104886
Create Date: 2026-08-21 13:00:58.804608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a974023dce47'
down_revision: Union[str, None] = 'b52c69104886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rest_outputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('default_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rest_outputs_token'), 'rest_outputs', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rest_outputs_token'), table_name='rest_outputs')
    op.drop_table('rest_outputs')
    # ### end Alembic commands ###
