"""add kafka and mqtt outputs tables

Revision ID: ac69cac79acc
Revises: 26e22bd3e2c7
Create Date: 2026-08-21 19:17:49.268012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac69cac79acc'
down_revision: Union[str, None] = '26e22bd3e2c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kafka_outputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('bootstrap_servers', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('events_per_second', sa.Float(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mqtt_outputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('broker_host', sa.String(length=255), nullable=False),
    sa.Column('broker_port', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('events_per_second', sa.Float(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mqtt_outputs')
    op.drop_table('kafka_outputs')
    # ### end Alembic commands ###
