"""add stop_probabilities to workflows

Revision ID: b3227be5dbd4
Revises: 9486abc9bbe0
Create Date: 2026-08-21 16:29:33.411916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b3227be5dbd4'
down_revision: Union[str, None] = '9486abc9bbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('stop_probabilities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'stop_probabilities')
    # ### end Alembic commands ###
