"""add enum_weights to entity_fields

Revision ID: feebc4d387cc
Revises: 27e7e338d49b
Create Date: 2026-08-21 13:29:48.552943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'feebc4d387cc'
down_revision: Union[str, None] = '27e7e338d49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_fields', sa.Column('enum_weights', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_fields', 'enum_weights')
    # ### end Alembic commands ###
